### ISSUE TITLE
Mitigate this bug in the CommentContentTagHelper

### ISSUE THREAD

**Issue by poppastring** [poppastring/dasblog-core#601]
Found this bug in @shanselman logs:

```
2021-11-16 02:11:06.535 +00:00 [Error] Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware: An unhandled exception has occurred while executing the request.
System.ArgumentNullException: Value cannot be null. (Parameter 'input')
at System.Text.RegularExpressions.Regex.Replace(String input, String replacement)
at DasBlog.Web.TagHelpers.Comments.CommentContentTagHelper.Process(TagHelperContext context, TagHelperOutput output) in /home/vsts/work/1/s/source/DasBlog.Web.UI/TagHelpers/Comments/CommentContentTagHelper.cs:line 24
at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
at Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner.<RunAsync>g__Awaited|0_0(Task task, TagHelperExecutionContext executionContext, Int32 i, Int32 count)
at AspNetCore.Themes_jinyang__CommentPartial.ExecuteAsync() in /home/site/wwwroot/Themes/jinyang/_CommentPartial.cshtml:line 14
```

We just need to guard against null reference before allowing the Regex check.

**Comment by zukomgwili** [comment]
Hi @poppastring. I will be happy to take this issue as well.

**Comment by poppastring** [comment]
@zukomgwili Sure thing! Thanks! 😃
